version = "3.7.15"
runner.dialect = scala3

rewrite.rules = [Imports]
rewrite.imports.sort = original
rewrite.imports.groups = [
  ["com.mojang\\..*"],
  ["net.minecraft\\..*"],
  ["net.neoforged\\..*"]
]

project.excludeFilters = [
  ".metals/.*",
]
